config/routes.rb
Rails.application.routes.draw do
  namespace :navegar do
    get 'index'
  end

  namespace :admin do
    get 'index'
   end
  namespace :about do
    get 'index'
  end
  resources :students, only: [:edit,:new, :show, :index]

  get 'welcome/index'
  root to:  'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/student.rb
class Student < ApplicationRecord
  paginates_per 5
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale

  def set_locale
    if params[:locale]
      cookies[:locale] = params[:locale]
    end
    if cookies[:locale]
      if I18n.locale != cookies[:locale]
        I18n.locale = cookies[:locale]
      end
    end
  end
end

app/controllers/navegar_controller.rb
class NavegarController < ApplicationController
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    #byebug
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def get_mat
    @student = Student.find[params[:matricula]]
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:name, :password, :password_confirmation)
    end
  end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/idiom_helper.rb
module IdiomHelper
end

app/helpers/navegar_helper.rb
module NavegarHelper
end

app/helpers/students_helper.rb
module StudentsHelper
  def translate_attribute(object = nil,method = nil)
    if object && method
      object.model.human_attribute_name(method)
    else
      "Informe os parâmetros corretamente"
    end
  end

  def choose_email(student)
    byebug
    emails = []
    nome = student.name
    5.times do |i|
      email = Faker::Internet.free_email(nome)
      email.split("@")[0] +"@uff.br"
      emails << email
    end
    return emails
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/about/index.html.erb
<h1><%= t('about') %></h1>
<p>O objetivo é criar uffmails!</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<title>UFF</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<%= stylesheet_link_tag    'application' %>
<%= stylesheet_link_tag    'welcome' %>

<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">

      <li class="navbar-brand">
        <%= image_tag("uff2.png", :alt => "rss feed", width: "100px") %>

          </li>
      <li class="nav-item active">

        <%= link_to welcome_index_path, class:"nav-link" do%>
         <span><%= t('home') %></span>
          <% end %>
      </li>
      <li class="nav-item">
        <%= link_to navegar_index_path, class:"nav-link" do%>
          <i class="material-icons">email</i>
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to about_index_path, class:"nav-link" do%>
          <span><%= t('about') %></span>
        <% end %>
      </li>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= t('idiom') %>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item"><%=link_to "Português", root_path(locale: 'pt-BR')%></a>
          <a class="dropdown-item" ><%=link_to "English", root_path(locale: 'en')%></a>
        </div>
      </li>
    </ul>
    <form class="form-inline">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-light my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
<!-- Add a background color and large text to the whole page -->
<div class="w3-sand w3-grayscale w3-large">

  <!-- Contact/Area Container -->
  <div class="w3-container" id="where" style="padding-bottom:32px;">
    <div class="w3-content" style="max-width:700px">
      <%= yield %>
    </div>
  </div>

  <!-- End page content -->
</div>

<!-- Footer -->
<footer class="w3-center w3-light-grey w3-padding-48 w3-large">
  <a href="http://www.uff.br/" title="STI-UFF" target="_blank" class="w3-hover-text-green">STI-UFF</a>
</footer>

<%= javascript_include_tag 'application' %>

<% if notice %>
  <%= javascript_include_tag do %>
    $.bootstrapGrowl('<%= notice %>', {
    type: 'success', // (null, 'info', 'danger', 'success')
    align: 'right', // ('left', 'right', or 'center')
    allow_dismiss: true, // If true then will display a cross to close the popup.
    stackup_spacing: 10 // spacing between consecutively stacked growls.
    });
  <% end %>
<% end %>


</body>

</html>

app/views/navegar/index.html.erb
<h1><%= t('uffmail') %></h1>
<p><%= t('messages.insira_matricula') %></p>
<form data-toggle="validator" role="form">
  <div class="form-group">
    <label for="exampleInputMatricula"><%= t('matricula') %></label>
    <input type="matricula" class="form-control sm" id="exampleInputMatricula" placeholder="Sua matrícula">
  </div>
  <div class="actions">
    <%= link_to new_student_path, class: "btn btn-primary" do%>
      <span><%= t('access') %></span>
    <% end %>
  </div>
  <div class="dropdown-divider"></div>
  <div class="form-group">
    <label>Não é estudante?</label>
    <%= link_to students_path, class: "btn btn-link" do%>
      <span><%= t('messages.click') %></span>
    <% end %>
  </div>
</form>

app/views/students/edit.html.erb
<div class="row">
  <% if @student.errors.any? %>
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
      <ul>
        <%= @student.errors.full_messages.each do |student| %>
          <li><%= student%></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <div class="card">
          <div class="card-header">
             "Edit Aluno"
          </div>
          <div class="card-body">


            <div class="panel-body">
              <div class="row">
                <div class="col-lg-6">

                  <%= form_with(model: @student, local: true) do |form| %>


                    <div class="form-group">
                      <%= form.label :name , class: "control-label"%>
                      <%= form.text_field :name, class:"form-control" %>
                    </div>
                    <div class="form-group">
                      <%= form.label :matricula, class: "control-label" %>
                      <%= form.text_field :matricula, class:"form-control" %>
                    </div>
                    <div class="form-group">
                      <%= form.label :email, class: "control-label", for:"inputEmail" %>
                      <%= form.text_field :email, class:"form-control"%>
                    </div>

                    <div class="form-group">
                      <%= form.label :password%>
                      <%= form.password_field :password, class:"form-control", placeholder:"Senha"%>
                    </div>

                    <div class="form-group">
                      <%= form.label :password_confirmation%>
                      <%= form.password_field :password_confirmation, class:"form-control", placeholder:"Confirmação de senha"%>
                    </div>

                    <div class="actions">
                      <%= form.submit class:"btn btn-primary"%>
                    </div>
                  <% end %>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Students</h1>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Matricula</th>
      <th>Email</th>
      <th></th>
      <th></th>
      <th><%= link_to new_student_path, class:"btn btn-link btn-lg"  do %>
          <i class="material-icons md-dark">fiber_new</i>

        <% end %>
      </th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= student.matricula %></td>
        <td><%= student.email %></td>
        <td><%= link_to student_path(student), class:"btn btn-link btn-sm" do %>
          <i class="material-icons md-dark">remove_red_eye</i>
          <% end %>
        </td>
        <td><%= link_to edit_student_path(student), class:"btn btn-link btn-sm" do %>
            <i class="material-icons md-dark">edit</i>

        <% end %>
        </td>
        <td><%= link_to edit_student_path(student) ,  class:"btn btn-link btn-sm" , method: :delete, data: { confirm: 'Are you sure?' } do%>
            <i class="material-icons md-dark">delete</i>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>

app/views/students/new.html.erb
<div class="row">
  <% if @student.errors.any? %>
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
      <ul>
        <%= @student.errors.full_messages.each do |student| %>
          <li><%= student%></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <div class="card">
          <div class="card-header">
            "Novo Aluno"
          </div>
          <div class="card-body">


            <div class="panel-body">
              <div class="row">
                <div class="col-lg-6">

                  <%= form_with model: @student do |form| %>

                    <div class="form-group">
                      <%= form.label :name , class: "control-label"%>
                      <%= form.text_field :name, class:"form-control" %>
                    </div>
                    <div class="form-group">
                      <%= form.label :matricula, class: "control-label" %>
                      <%= text_field_tag(params[:matricula], class:"form-control" )%>
                    </div>

                    <div class="form-group">
                      <%= form.label :email, class: "control-label", for:"inputEmail" %>
                      <%= form.select :email, [choose_email(:name)] %>
                     </div>

                    <div class="form-group">
                      <%= form.label :password%>
                      <%= form.password_field :password, class:"form-control", placeholder:"Senha"%>
                    </div>

                    <div class="form-group">
                      <%= form.label :password_confirmation%>
                      <%= form.password_field :password_confirmation, class:"form-control", placeholder:"Confirmação de senha"%>
                    </div>

                    <div class="actions">
                      <%= form.submit class:"btn btn-primary"%>
                    </div>
                  <% end %>

                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>
<%= render partial: 'students/form',
           locals: { action_message: t('messages.show') } %>

<%= link_to 'Back', students_path %>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <h2 class="display-4"><%= t('messages.welcome') %></h2>
  <p class="lead">Utilize sua matrícula para criar, editar ou deletar uma conta.</p>
  <hr class="my-4">
  <p>Se você é administrador fique atento!</p>

    <%= link_to students_path class: "btn btn-primary" do %>
    <span><%= t('messages.read') %></span>
    <% end %>

</div>